### ISSUE TITLE
Version 2.0.0 Tracking

### ISSUE THREAD

**Issue by daniel-wtd** [while-true-do/ansible-skeleton#56]
This is the tracking issue for Version 2.0.0 and should also contain discussions for other features, proposed by the community.

Release 2.0.0 should contain additions, which will help with other concepts of Ansible and roles should be only one part of it.

-    [ ] usage and guidance for mazer
-    [ ] concepts of multi-role repositories
-    [ ] concepts and usage of apb
-    [ ] concepts and usage of ansible-play-* repositories
-    [ ] concepts and usage of molecule templates (not released, yet)

Furthermore, we should start to split the documentation and provide lot's of details for testing and using skeletons.
